kubectl apply -f k8s/currencyexchange-deploy.yaml
kubectl apply -f k8s/destination-v3-deploy.yaml
kubectl apply -f k8s/hotel-v3-deploy.yaml
kubectl apply -f k8s/carrental-v3-deploy.yaml
kubectl apply -f k8s/ui-deploy.yaml
kubectl apply -f k8s/destination-service.yaml
kubectl apply -f k8s/hotel-service.yaml
kubectl apply -f k8s/carrental-service.yaml
kubectl apply -f k8s/currencyexchange-service.yaml
kubectl apply -f k8s/ui-service.yaml
kubectl apply -f k8s/mongo-secret.yaml