apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrental-v3
  labels:
    app: carrental
    version: v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carrental
      version: v3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: carrental
        version: v3
    spec:
      containers:
      - image: beetravels/carrental-v2:node-v1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9102
        name: carrental
        env:
          - name: PORT
            value: "9102"
          - name: HOST_IP
            value: carrental
          - name: SCHEME
            value: http
          - name: DATABASE
            value: mongodb
          - name: MONGO_CONNECTION_URL
            value: <YOUR URL HERE>
          - name: SERVICE
            value: car-rental-v3
          - name: DATABASE_CERT
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: dbsecret
        resources:
          limits:
            cpu: 200m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 400Mi
      restartPolicy: Always
      
