apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hotel-v1
  labels:
    app:  hotel
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  hotel
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  hotel
        version: v1
    spec:
      containers:
      - image: beetravels/hotel-v1:node-v1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 9101
        name:  hotel
        env:
          - name: PORT
            value: "9101"
          - name: HOST_IP
            value: hotel
          - name: SCHEME
            value: http
          - name: LOG_LEVEL
            value: info
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
      
